apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
  labels:
    purpose: config
    env: dev
data:
  COURSE: "DevOps With AWS"
  DURATION: "120Hours"
  TRAINER: "Sivakumar"
  STUDENT: "Lakshminarasimha"  
  